# Makefile
default:
	gcc locate.c -o loc -I/usr/local/include -L/usr/local/lib -lIP2Location -Wall 
# CC=gcc
# CFLAGS=-Wall -Wextra -O2
#
# server: server/main.c
# 	$(CC) $(CFLAGS) -o rcw server/main.c
#
# clean: rm -f rcw
